Repository CryptoScamDB/cryptoscamdb.org, pull requests merged in 2018-11, with the labels that each got.

#28 Frontend changes to account for backend api changes
  src/app.ts
  src/views/pages/address.ejs
  src/views/partials/search.ejs
  src/views/static/js/address.js
  src/views/static/js/search.js
Labels: in progress

#31 Implement XHR for various pages
  package-lock.json
  package.json
  src/app.ts
  src/views/pages/404.ejs
  src/views/pages/address.ejs
  src/views/pages/coin.ejs
  src/views/pages/domain.ejs
  src/views/pages/ip.ejs
  src/views/pages/scams.ejs
  src/views/pages/verified.ejs
  src/views/partials/stats.ejs
  src/views/static/css/domain.css
  src/views/static/css/scams.css
  src/views/static/js/address.js
  src/views/static/js/coin.js
  src/views/static/js/ip.js
  src/views/static/js/scams.js
  src/views/static/js/verified.js
Labels: size/XL

#32 Minor fixes for scams page
  package-lock.json
  package.json
  src/views/pages/scams.ejs
  src/views/static/css/scams.css
  src/views/static/js/scams.js
Labels: size/XXL
